[package]
name = "Examples"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
StableCoin1 = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"